main:
  - name: Research
    url: research
    weight: 10
  - name: Teaching
    url: teaching
    weight: 20
  - name: Publications
    url: publication
    weight: 30
  - name: News
    url: news
    weight: 40
  - name: Contact
    url: contact
    weight: 50


# sidebar:
#   - identifier: more
#     name: Still need help?
#     params:
#       type: separator
#     weight: 1
#   - identifier: community
#     name: "Community"
#     pageRef: "/community"
#     weight: 2
#   - identifier: hugoDocs
#     name: "Hugo Docs ↗"
#     url: "https://docs.hugoblox.com"
#     weight: 3
